### ISSUE TITLE
Convert/Use Vukit components as SFC

### ISSUE THREAD

**Issue by ydennisy** [vuikit/vuikit#101]
How would one go about to convert the Vuikit components into SFCs, is this possible?

Main reason for asking, is it becomes hard to debug the library vs being able to manipulate the SFC.

More context:
`<vk-modal-close v-on:click="$emit('clickedx')" large></vk-modal-close>` also I have tried `<vk-modal-close v-on:click.native="$emit('clickedx')" large></vk-modal-close>`

I am using the above, but cannot find anyway to do anything based on the X being clicked...

Another update:

placing any other regular element such as:
`<button @click="setFullConsent()">Click!!</button>` works perfectly!

**Comment by miljan-aleksic** [comment]
That's because in my stupidity I assumed the close button will be always used the same way, and hardcoded it behaviour overriding any events...

I will revert that back, meantime you can load the close element and use it directly. All elements used by a component are exported but not globally registerd, so you could use them instead like this:

```
<vk-modal>
  <el-modal-close @click="..."/>
</vk-modal>
```
```
import { ElModalClose } from 'vuikit/lib/modal'

export default {
  components: { ElModalClose }
}
```

**Comment by ydennisy** [comment]
Ok thanks @miljan-aleksic what about the more global Q, being able to take each component and import it as SFC into a project - do you think that is a) possible? b) useful?

Dennis

**Comment by miljan-aleksic** [comment]
The SFC are nice to compose an App, but not for building a library. Basically the library requires low level control that is no possible with SFC. Converting a raw code into SFC is not possible.

**Comment by miljan-aleksic** [comment]
I have been working on a better separation of concerns that might help to keep the component core as SFC. Plus the rollup compatibility with vue is much better now. I will give it a shot :)

**Comment by ydennisy** [comment]
Thanks @miljan-aleksic
