### ISSUE TITLE
keep-alive with Vuikit Tabs

### ISSUE THREAD

**Issue by paul-muckypuddle** [vuikit/vuikit#102]
Is it possible to use the `keep-alive` tags with `vk-tabs` - I can't figure out if my syntax is wrong or if it's unsupported

**Comment by miljan-aleksic** [comment]
It's supported, the syntax is `<vk-tabs keep-alive>...</vk-tabs>`.

**Comment by paul-muckypuddle** [comment]
Superb, thanks!
