### ISSUE TITLE
v-show (instead of v-if) for Tabs

### ISSUE THREAD

**Issue by paul-muckypuddle** [vuikit/vuikit#103]
Is it possible to use v-show instead of v-if in the Tabs component? Looking to have all components within those tabs activated at load time rather than activated 'on tab'

**Comment by miljan-aleksic** [comment]
It's not with the current approach. Why you need them activated upfront?

**Comment by paul-muckypuddle** [comment]
Using OpenTok for WebRTC, streams are published in a tab but it's not the first one

**Comment by miljan-aleksic** [comment]
Perhaps you can separate the logic from the presentation, using the tabs only to display what has already been inited somewhere else.

**Comment by paul-muckypuddle** [comment]
Hahah isn't Vue all about mixing logic and presentation in single file components? Well, 'presentational' logic I guess...

**Comment by miljan-aleksic** [comment]
You guessed well. Keep your presentational components scoped, only aware of the data they recieve through props. All the logic to retrieve that data should be placed in a higher level component.

**Comment by paul-muckypuddle** [comment]
You're not wrong. I'll look into refactoring this - just talking through the problem has helped with my understanding, so thank you.
