### ISSUE TITLE
offcanvas closing error

### ISSUE THREAD

**Issue by biggless** [vuikit/vuikit#105]
I have small snippet:
```
<template>
  <vk-offcanvas-content>
    <vk-button v-on:click="toggleNavigation">Open</vk-button>
    <vk-offcanvas :show="show">
      <vk-offcanvas-close @click="toggleNavigation"/>
      <h3>Title</h3>
      <p>Offcanvas content</p>
    </vk-offcanvas>
  </vk-offcanvas-content>
</template>

<script>
export default {
  data () { return { show: false } },
  methods: {
    toggleNavigation () { this.show = !this.show }
  }
}
</script>
```

After offcanvas closing I'm getting this error:
![screen shot 2018-06-22 at 10 49 09 am](https://user-images.githubusercontent.com/696810/41764544-18aa28e6-760a-11e8-80dd-78159ee801ee.png)
![screen shot 2018-06-22 at 10 49 25 am](https://user-images.githubusercontent.com/696810/41764548-1b7b4050-760a-11e8-8e09-7d17bc4555f6.png)

**Comment by miljan-aleksic** [comment]
Hi, please reproduce the issue on [Codepen](https://codepen.io/vuikit/pen/RMYWGg) or similar.

**Comment by biggless** [comment]
https://codepen.io/anon/pen/RJyqRg?editors=1011 but it's not reproducing there. Should I do this in separated repo? Will it help to solve the problem?

**Comment by miljan-aleksic** [comment]
[Codesandbox](https://codesandbox.io/) is more advanced, try to set your entire project there. Or anywhere, I just need to see it reproduced live.
