### ISSUE TITLE
usage with router and vk-button-link

### ISSUE THREAD

**Issue by PhilThurston** [vuikit/vuikit#106]
We notice a difference between router-link and vuikit.

`<router-link to="/page1" tag="button">Show page one</router-link>`
`<vk-button-link type="primary" href="/page1">Show page one</vk-button-link>`

router-link is instant and vk-button seems to be loadiing the actual url set like a normal `a href`.  functionality that we'd rather avoid.

We saw in #96 that you suggested using tags with router-link to keep this working. Here is what we've tried:

` <router-link to="/page1" tag="vk-button">List page one</router-link>` - This works but you can't apply additional stylings.

and

` <router-link to="/page1" tag="a" class="uk-button uk-button-primary">List page one</router-link>` - this seems to be the only thing that works but completely bypasses the vuikit styled button. Will this break anything or cause issues? Is there a simpler way to do this? Lastly are there plans to have things work well with  vue-router or is that out of scope?

**Comment by miljan-aleksic** [comment]
Hi Phil,

no library should be aware of the existence of a router, the same way it should not be aware of any plugin. The issue you experience must be solved in vue-router, an aknowledge issue by the Vue team.

Meantime you can do the workarounds you describe or this simpler one:

```
<router-link tag="span" to="...">
  <vk-button-link..../>
</router-link>
```
