### ISSUE TITLE
Vue variables inside of table structure.

### ISSUE THREAD

**Issue by PhilThurston** [vuikit/vuikit#107]
I wanted to reference #46 and suggest a possible improvement. 

`<vk-table-column title="title7"><a v-bind:href="data.data7" target="_blank">View Item</a></vk-table-column>`

It seems like it would be much easier to and cleaner to have it work in this fashion. Just being able to pass in variables like you would with the cell in normal vue. How difficult would this be?

**Comment by miljan-aleksic** [comment]
That ticket is referencing Vuikit 0.6, in 0.8 is possible to use [slots](https://vuikit.js.org/guide/table#slots), which seems is what you are looking for.
