### ISSUE TITLE
Sticky tab header?

### ISSUE THREAD

**Issue by gurpal2000** [vuikit/vuikit#110]
Is it possible to have  a sticky tab header? The below seems to stick the dynamic content in the body as well? Or should i emulate using a button group/nav?

```
  <vk-sticky>
    <vk-tabs keep-alive align="justify">
      <vk-tabs-item title="Updates">
        <updates-tab></updates-tab>
      </vk-tabs-item>
      <vk-tabs-item title="Installed">
        <installed-tab></installed-tab>
      </vk-tabs-item>
    </vk-tabs>
  </vk-sticky>
```

**Comment by miljan-aleksic** [comment]
Currently the only way to do that would be to create a custom tabs components, as the default tabs implementation doesn't allow separation of the tabs from the content. You can reuse the tabs vuikit tabs elements to make the process easier.
