### ISSUE TITLE
Vuikit theme import error in nuxt plugin

### ISSUE THREAD

**Issue by steven-ferrer** [vuikit/vuikit#114]
Hi @miljan-aleksic, thank you so much for this amazing work that you did!

I tried importing vuikit via nuxt plugins but I got an error. So, the way it should be imported in the docs was:

```javascript
import Vue from 'vue'
import Vuikit from 'vuikit'
import VuikitIcons from '@vuikit/icons'

import '@vuikit/theme'

Vue.use(Vuikit)
Vue.use(VuikitIcons)
```

But when I run the nuxt app, i get the following error:

![image](https://user-images.githubusercontent.com/19186904/43752633-89949aca-9a34-11e8-8529-47f1714c48e6.png)

I have managed to get around this issue by importing it like this:

```javascript
import Vue from 'vue'
import Vuikit from 'vuikit'
import VuikitIcons from '@vuikit/icons'

import '@vuikit/theme/dist/vuikit.min.css'

Vue.use(Vuikit)
Vue.use(VuikitIcons)
```

Or maybe I missed something?

Here is the repo of the project: https://github.com/steven-ferrer/my-vuikit-project

**Comment by miljan-aleksic** [comment]
Hi @steven-ferrer, I'm glad you like it :)

That's quite strange, as the error is referencing the same exact file you are manually importing... I will change it to point to the uncompressed version as that could be the issue and anyway is what would the app expect.
