### ISSUE TITLE
Icons are not working in Internet Explorer 11

### ISSUE THREAD

**Issue by DanielEgbers** [vuikit/vuikit#117]
Icons are not working in Internet Explorer 11, because for some reason all &lt;svg&gt;-Tags are empty.

Internet Explorer 11             |  Firefox
:-------------------------:|:-------------------------:
![a](https://user-images.githubusercontent.com/27849724/44546580-a4c18600-a718-11e8-9851-a31fe9eef56f.png)  | ![firefox_2018-08-23_20-49-49](https://user-images.githubusercontent.com/27849724/44546586-a8550d00-a718-11e8-9a77-975a482dcfc0.png)
![image](https://user-images.githubusercontent.com/27849724/44546714-13064880-a719-11e8-924f-3a305c3a31d3.png) | ![image](https://user-images.githubusercontent.com/27849724/44546697-084bb380-a719-11e8-867a-1f8c67b9b0d5.png)

To reproduce it just open https://vuikit.js.org/guide/icons/ in Internet Explorer 11 or create a basic vue project with vuekit and add a icon control or any control that uses icons (e.g. Offcanvas (Close-Button) or Spinner)

Icons from UIkit itself are working in Internet Explorer 11 (see https://getuikit.com/docs/iconnav)

**Comment by DanielEgbers** [comment]
Thanks. &lt;vk-icons-...&gt;-Tags are working now, but the X of the offcanvas and the circle of the spinner are still not showing up

**Comment by miljan-aleksic** [comment]
You are totally right. I have detected and fixed icons on vk-spinner, vk-pagination, vk-notification, vk-navbar-toggle, vk-modal-close, vk-offcanvas-close, vk-tabs-dropdown. Please update to 0.8.6.

**Comment by DanielEgbers** [comment]
All icons are working now in Internet Explorer 11 with vuikit 0.8.6 and @vuikit/icons 0.9.0-next . Thank you very much.

**Comment by miljan-aleksic** [comment]
I'm afraid I had to revert these changes and that the fix will have to wait a major revision.
