### ISSUE TITLE
0.8.6 has broken close icons for modals (building with Parcel)

### ISSUE THREAD

**Issue by mvlabat** [vuikit/vuikit#118]
Hi! Thanks a lot for the library.

I try to get it working with Parcel build tool (https://parceljs.org/), but I get the following error on compilation:

```
🚨  /Users/vladyslavbatyrenko/nodejs/platformio/frontend/node_modules/vuikit/lib/modal.js:13:22: Cannot resolve dependency './icons/close' at '/Users/vladyslavbatyrenko/nodejs/platformio/frontend/node_modules/vuikit/lib/icons/close'
  11 | import { addClass, removeClass } from './util/class';
  12 | import { mergeData } from './util/vue';
> 13 | import IconClose from './icons/close';
     |                       ^
  14 | import IconCloseLarge from './icons/close-large';
  15 | import EventsMixin from './mixins/events';
  16 | import { css } from './util/style';
```

Posted this issue to you guys first. I can see that you have your own `vuikit-icons-loader` for webpack, so I assumed Parcel would require a plugin as well.

**Comment by mvlabat** [comment]
Update: got everything working with 0.8.5 and with Parcel.

**Comment by miljan-aleksic** [comment]
Hi! You are welcome! Please try with 0.8.8 and let me know :)

**Comment by mvlabat** [comment]
Thanks for the release!
Unfortunately, this doesn't work for me either, but now it has another error (so it seems to be a progress :) ):
```
Server running at http://localhost:1234
🚨  /Users/vladyslavbatyrenko/nodejs/platformio/frontend/node_modules/vuikit/lib/icons/close.js:11:14: Cannot resolve dependency 'close.vue?rollup-plugin-vue=script.js'
   9 |
  10 | import script__default from 'close.vue?rollup-plugin-vue=script.js';
> 11 | export * from 'close.vue?rollup-plugin-vue=script.js';
     |               ^
  12 |
  13 | /* script */
  14 |             var __vue_script__ = script__default;
```

**Comment by miljan-aleksic** [comment]
Ok, I will have to take a deeper look into this... seems I broke the build process.

**Comment by miljan-aleksic** [comment]
Well, had to go all way down to 0.8.5 and stick to that code. Its released as 0.8.9 now. Let me know if you still have issues.

**Comment by mvlabat** [comment]
@miljan-aleksic, I've got a new error again :(
Now it's
```
yarn run v1.9.4
$ parcel index.html --no-hmr
Server running at http://localhost:1234
🚨  /Users/vladyslavbatyrenko/nodejs/platformio/frontend/node_modules/vuikit/src/library/button/components/button.js: ENOENT: no such file or directory, open '/Users/vladyslavbatyrenko/nodejs/platformio/frontend/node_modules/vuikit/src/library/button/components/button.js'
Error: ENOENT: no such file or directory, open '/Users/vladyslavbatyrenko/nodejs/platformio/frontend/node_modules/vuikit/src/library/button/components/button.js'
```

Really grateful for your support and sorry I have to keep you from new fixes

**Comment by miljan-aleksic** [comment]
Somewhere in your code you are trying to import `vuikit/src/library/button/components/button.js`, change it to `vuikit/lib/button.js`.

**Comment by mvlabat** [comment]
Sorry, didn't pay enough attention, that was the case indeed!
But it seems to me that this is a lot of breaking changes for a minor patch release (

**Comment by miljan-aleksic** [comment]
I have released a new version that include the src folder as well, you can use your previous code as well, but do so only if you know why. By default always import from the lib folder.

**Comment by mvlabat** [comment]
@miljan-aleksic , thanks a lot! That's the best support I've ever received in my open source experience )

The thing is that I accidentally imported it from `/src` folder, because that's what WebStorm suggested, when I was typing `<vk-button>` (having not imported VkButton component itself yet). And that was very convenient, because WebStorm automatically added import statement and included VkButton in my component - this IDE has great Vue.js support. But it doesn't do the same with the components in `lib`.

What if we consider similar project layout for `lib` components as well? If there's no significant drawback, it can improve user experience for IDE users quite a lot. If you agree/want to discuss it, I think it would make sense to create a new issue for this feature.

**Comment by miljan-aleksic** [comment]
:)

The issue about using src is because nowdays the src require compiling, from es6 to es5 for example and compiling the code from your project would most likely rise issues. The lib folder has the code compiled and ready to be imported, and similarly the dist has the entire library in different formats.

As far as I know, there is no standard using the lib folder, it could be done even without the lib, `vuikit/button`, while there is some kind of common pattern using src. Thus, I don't know if there is anything to do about this.
