### ISSUE TITLE
vuikit 

### ISSUE THREAD

**Issue by lephenix1234** [vuikit/vuikit#125]
how to use vuikit for specific component vuejs

**Comment by miljan-aleksic** [comment]
Sorry, can you be more specific about your usecase?

**Comment by lephenix1234** [comment]
I'm writing a vuejs application
I have an A component that I coded in pure css
and another component B with vuikit
when I do view.use(Vuikit) it impacts my entire application
when I only want it to affect component B

**Comment by miljan-aleksic** [comment]
In your B component do something like this.

```js
import { Button, ButtonLink } from 'vuikit/lib/button'

export default {
  components: {
    VkButton: Button,
    VkButtonLink: ButtonLink
  }
}
```

**Comment by lephenix1234** [comment]
Thank you, my friend.
God bless you
