### ISSUE TITLE
Notifications does not display

### ISSUE THREAD

**Issue by Ardraws** [vuikit/vuikit#126]
HI, 

Im trying to display notifications dynamically but when I push on the array the message is correctly added to it but does not display on the notifications element.

**Comment by miljan-aleksic** [comment]
Hi, don't push to the array, replace it entirely with a fresh copy plus the new record.

**Comment by Ardraws** [comment]
Thanks you for the fast repply somehow I had an error in my data() so now it works fine by pushing the array. By the way Great Job on Vuikit ! :)
