### ISSUE TITLE
custom icons

### ISSUE THREAD

**Issue by johnzeus14** [vuikit/vuikit#129]
i did not like the uikit icon so i download some nice packs from flaticon.com..in svg format but i could not integrate it..please tell me how??

**Comment by miljan-aleksic** [comment]
Hi John,

there is nothing unique about Vuikit Icons, they are just raw SVG icons wrapped in a component for conveniance. Thats usually how Vue projects would expect them, but it is not necessary, any other way of implementing SVG icons would work. Try the one that works best for you, I would start with the way flaticon.com suggests.

**Comment by miljan-aleksic** [comment]
Ok, then follow [this short guide](https://vuikit.js.org/guide/icons). If you have a big collection of icons [this article](https://alligator.io/vuejs/using-svg-icons/) may be of help.

**Comment by johnzeus14** [comment]
Thank you miljian ia m so greatfull, it worked  perfectly..you are an awesome dude..have a happy new year

**Comment by miljan-aleksic** [comment]
You are welcome. Happy New Year :)
