### ISSUE TITLE
_uikit2.default.modal is not a function

### ISSUE THREAD

**Issue by Async0x42** [vuikit/vuikit#13]
Trying out vuikit for the first time, but with a very setup in my project I get the following error:
`_uikit2.default.modal is not a function`

in
```
	  methods: {
	    initModal: function initModal() {
	      var vm = this;
	      this.UImodal = _uikit2.default.modal(this.$els.modal, this.options);
	      this.UImodal.on('show.uk.modal', function () {
	        vm.show = true;
	        vm.$emit('show');
	        setTimeout(function () {
	          vm.UImodal.resize();
	        }, 1);
	      });
	      this.UImodal.on('hide.uk.modal', function () {
	        vm.show = false;
	        vm.$emit('hide');
	      });
	    }
	  }
```

I setup Vue.use(VuiKit) in my main script, and am using the following template in a component. On rendering, it throws the above error.
```<template>
  <div>
    <vk-modal overflow>
      <template slot="header">Headline</template>
      <div>Test</div>
      <template slot="footer">Footer</template>
      <template slot="caption">Caption</template>
    </vk-modal>
  </div>
</template>
```
Any idea what could be causing this? On debugging, _uikit2.default exists, but there's no 'modal' anywhere inside of it when I browse through all the properties.

Using Vue 1.0.26 w/ ES6 & Webpack

**Comment by miljan-aleksic** [comment]
Hi! How are you loading the UIkit dependency?

**Comment by Async0x42** [comment]
Hmm, I'm a bit new to using webpack, so I had thought that ModalBase importing uikit as UI would import it as required (the js at least). Aside from that, I was trying import 'uikit' (or require('uikit')), however neither worked.

**Comment by miljan-aleksic** [comment]
In some future revision will be probably porting most of the JS removing the dependency of both UIkit js and jQuery. Meantime as UIkit is not well optimized for node you need to load it upfront, as well as jQuery, in your HTML file.

Checkout Vuikit [index.ejs](https://github.com/vuikit/vuikit/blob/develop/index.ejs) as example. Express.js allows to set folders as statics paths, both `node_modules/jquery/dist`and `node_modules/uikit/dist/js` are set as `static/js` and the is just about adding the script `<script src="static/js/asset.js"></script>`. That's how the assets are loaded without including them in the app bundle.

**Comment by Async0x42** [comment]
Ah okay got it, thanks for clarifying! I wasn't sure if it was some simple mistake I was missing or not; I ran into the jQuery issues with various other plugins & webpack before.
