### ISSUE TITLE
 Anonymize classes name

### ISSUE THREAD

**Issue by AleeeKoi** [vuikit/vuikit#133]
Hi, there's any way to avoiding classes name collisions with other frameworks or uikit version?
In my case i need to create a plugin app that can be used in other existing sites that have their existing css style.
I can easily wrap uikit css inside a global parent class but i don't know if parent site declare same classes name globally.
Enabling css modules and mapping all css can be a solution but doesn't work with vuikit components because vuikit class name are not accessible.
Any ideas? Thank you

**Comment by miljan-aleksic** [comment]
In the UIkit documentation they explain how to change the prefix for a custom theme, they build a script for that.

That would solve the CSS part, but yet Vuikit will render the elements with the default `uk-` prefix and there is no option to change that. You could try creating a custom script that will replace all 'uk-' in the final complied vuikit.js code.

**Comment by AleeeKoi** [comment]
Yes, it could be a (not easily) solution.
I think using postcss plugin I can prefix classes easily.
There’re any webpack plugins for changing components classes name during or post rendering?
Thanks

**Comment by miljan-aleksic** [comment]
Components classes are not standarized, furthermore the code you want to change is rendered using functional components, which are simple functions.

A good regex will do the trick, but anyway there are webpack plugins that allows you to do changes during it lifecycle.
