### ISSUE TITLE
Alert Bug

### ISSUE THREAD

**Issue by iamshulz** [vuikit/vuikit#138]
How do I use alert same on HTML. I am unable to make it similar to Uikit

![image](https://user-images.githubusercontent.com/20100579/88197376-fb24ff80-cc74-11ea-86c3-cbdeebab6dfd.png)

**Comment by miljan-aleksic** [comment]
Please provide a code that will provide a context to better understand your issue.

**Comment by iamshulz** [comment]
I have now skipped using Vuikit and transferred to the UIkit instead
