### ISSUE TITLE
vuikit tabs type error?

### ISSUE THREAD

**Issue by JanKybe** [vuikit/vuikit#140]
Hi, i have weird problem with the vuikit tabs, i can use every other component in the vuikit, but tabs gives me error:

`[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'key' of undefined"`

I copy/paste the documentation example just to see if it works, and it still gives me error, weird thing is that it once worked but now it seemingly just stopped working, even though i didnt change any code in main.vue

vuikit is imported and everything should be fine with that, but just that one error that i cant get over.

```
<vk-tabs>
  <vk-tabs-item title="Item">Hello!</vk-tabs-item>
  <vk-tabs-item title="Item">Hello again!</vk-tabs-item>
  <vk-tabs-item title="Item">Bazinga!</vk-tabs-item>
  <vk-tabs-item title="Disabled" disabled icon="lock"></vk-tabs-item>
</vk-tabs>
```

**Comment by miljan-aleksic** [comment]
Hi, please reproduce this in some JS playground, like JSFiddle or CodeSandbox and will take a look.

**Comment by JanKybe** [comment]
Hi, did the CodeSandbox and it works there, but while doing the same thing in my project it randomly fails, any idea what might cause that kind of problem ? 

im using Vue 2, and Typescript, thought maybe Typescript might cause problems, but im not really sure, i used same example, the vuikit import is done the same way as in documentation so i doubt the problem is there

**Comment by JanKybe** [comment]
Typescript was probably the problem, created new project without it and there it worked fine. I'll close that issue
