### ISSUE TITLE
Getting vuikit to work without webpack and ES6

### ISSUE THREAD

**Issue by vuchl** [vuikit/vuikit#17]
Hi there!

I'm having troubles getting vuikit to work when I'm only in the browser and serving via Apache. I have this index.html:
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <script src="/js/jquery.js"></script>
        <script src="/js/uikit.js"></script>
        <script src="/js/vue.js"></script>
        <script src="/js/vuikit.js"></script>
        <link href="/css/uikit.css" rel="stylesheet">

    </head>
    <body>
        <app></app>
        <script>
            
            new Vue({
                el: 'app',
                template: '@{{ number }}',
                data: function() {
                    return ({number: 1})
                },
            })

        </script>
    </body>
</html>
```
jQuery is 2.2.4, Vuejs is 1.0.26 and Uikit is 2.26.4. I `git clone`d the repo and after `npm install` i ran `npm run build`and used the created `dist/vuikit.js` in my project.

I still get the message that "ReferenceError: vue is not defined...,t.webpackPolyfill=1),t}},function(t,e){t.exports=**vue**},function(t,e,n){"use stri...vuikit.js (Row 7, Column 27256)".

I'm not the greatest NPM/Node master but from going through the files i can see that it builds against production as the environment.

What am I missing? Normal Vue.js usage is possible.

Edit: Don't mind the @ infront of the mustache syntax, I use laravel and escape the mustaches that way to keep them in the file.

**Comment by miljan-aleksic** [comment]
Hi @vuchl :)

You are not missing anything, it happens that the dist build was referencing Vuejs as external resource `vue` instead of `Vue`. While this is correct in node is not in the browser. It is fixed now in the develop branch, can you try it out and feedback?

Thanks!

**Comment by vuchl** [comment]
Hey @miljan-aleksic !

For someone who may need it too: I cloned the repo again via `gt clone https::/github.com/vuikit/vuikit.git` (since `develop`is the current working branch), and used `npm install` to install all the dependencies. After that I `npm run build` and used the `vuiikit.js` from the dist folder to serve them staticallyas in the template above described.

No everything works as intenden. Huge thanks!

P.S. also thanks for your uikit.css. I like the look of it better then the default flat theme.

**Comment by miljan-aleksic** [comment]
Great, thanks!

**Comment by miljan-aleksic** [comment]
BTW, the UIkit theme is a fork from Pagekit admin one, if you want the less files let me know.
