### ISSUE TITLE
Button demo - iconLeft and iconRight on <vk-button-link> not working

### ISSUE THREAD

**Issue by vuchl** [vuikit/vuikit#19]
Hey @miljan-aleksic !

I can not find the error currently but on the demo page the default `<vk-button>` is displaying the `iconLeft` and `iconRight` icons correctly. In the `<vk-button-link>` the icons don't show up.

This is the error message Vue dev tools gives me on the local dev build:
```
vue.js:1023 [Vue warn]: Error when evaluating expression "iconClass(iconLeft)": TypeError: scope.iconClass is not a function (found in component: <vk-button-link>)
```

My best guess is the fact that `<vk-button-link>` [inherits](https://github.com/vuikit/vuikit/blob/develop/src/views/Button/ButtonLink.vue#L46-L48) from `<vk-button>` and since the scope is different. But I have no clue for a pull request :disappointed: 

Regards Sebastian

**Comment by miljan-aleksic** [comment]
Hi there,

set the icons as the Buttons slot, you will have more control over how to render them. I am anyway considering to remove them..

```html
<vk-button>Button <i class="uk-icon uk-icon-flag"></i></vk-button>
```
