### ISSUE TITLE
doc typo on progress

### ISSUE THREAD

**Issue by mediafigaro** [vuikit/vuikit#26]
Hello : progress contains pagination component here : http://vuikit.github.io/vuikit/#!/progress 

The vk-**progress** component renders a progress bar.
PROPS
SLOTS
EXAMPLE
<vk-**pagination** :progress="100"
  color="warning"
  stripe>
  40%
</vk-pagination>

**Comment by miljan-aleksic** [comment]
Thanks, but can you be more specific?

**Comment by mediafigaro** [comment]
isn't there a typo as it should be called vk-progress and not vk-pagination ?
![image](https://cloud.githubusercontent.com/assets/18629935/18509367/84de3190-7a78-11e6-859c-6e446b858bda.png)

**Comment by miljan-aleksic** [comment]
Ah, true! Fixed in dev but anyway, VkProgress has been deprecated in vuikit next as any other component that was acting as just UIkit alternative syntax.
