### ISSUE TITLE
[next] Button doesn't emit clicks

### ISSUE THREAD

**Issue by sunabozu** [vuikit/vuikit#27]
Hi!

I'm trying to experiment with the *next* branch, and I'm a bit confused about behaviour of the `Button` component. It doesn't produce clicks. I subscribe to the `@click=""` event, but when I press the button nothing happens. The [template](https://github.com/vuikit/vuikit/blob/next/src/lib/Button.js#L56) looks simple except this `{...data}` part. Perhaps it has something to do with my problem? Never seen it before in Vue tempates.

``` vue
<button type={ this.type } disabled={ this.disabled } {...data}>
    { this.$slots.default }
</button>
```

**Comment by vuchl** [comment]
Just for your information, I think the `{...data}` is ES6 parameter destructuring.

**Comment by miljan-aleksic** [comment]
@sunabozu, in Vue 2 the native events must be listened with the modifier `native`, eg. `@click.native="..."`.

@vuchl is right, that code is some nice ES6 sugar syntax. The templates in vuikit next are replaced with render functions where you would see raw JS or JSX.

**Comment by sunabozu** [comment]
@miljan-aleksic 
Oh, that explains everything. Thank you!
I didn't know about such a change in Vue 2.0, but I guess it makes sense.
