### ISSUE TITLE
v0.6.0

### ISSUE THREAD

**Issue by SaidTayebi** [vuikit/vuikit#28]
Hello,

Do you have an estimated relase date for the version 0.6.0 ?

Thanks.

**Comment by miljan-aleksic** [comment]
Right after Vue 2.0 becomes stable.

**Comment by SaidTayebi** [comment]
Thanks !

**Comment by SaidTayebi** [comment]
Can you make the next branch available for install ? Like in vue.js vue@next

**Comment by miljan-aleksic** [comment]
Done, you can access the dist files using rawgit.com, eg: 

```
https://cdn.rawgit.com/vuikit/vuikit/next/dist/vuikit.js - production
https://rawgit.com/vuikit/vuikit/next/dist/vuikit.js - development
```

**Comment by SaidTayebi** [comment]
I got an error in both versions:
Uncaught ReferenceError: moment is not defined

**Comment by miljan-aleksic** [comment]
Moment.js has become an external dependency used by Calendar and Datepicker. You need to load it first, or create your own build without those two.

**Comment by SaidTayebi** [comment]
Works fine with a custom build. Thanks !
