### ISSUE TITLE
Bower?

### ISSUE THREAD

**Issue by davidkhess** [vuikit/vuikit#29]
Any chance of making Vuikit available on bower?

**Comment by miljan-aleksic** [comment]
Honestly, don't see any advantage. What does Bower solve that you can't with NPM?

**Comment by davidkhess** [comment]
Nothing. But some people and projects use bower, some use npm. Forcing people to use npm to manage a dependency on a bower based project could discourage adoption.

Making it available via bower will potentially increase adoption.

**Comment by miljan-aleksic** [comment]
Will keep that in mind, but taking in consideration Bower usage is decreasing and supporting two methods for the same feature is not a good idea, I must decline. At least until further notice :)

**Comment by davidkhess** [comment]
Ok. As a data point, Vue supports bower.

**Comment by miljan-aleksic** [comment]
Do you happen to know how is done by Vue? I can't find any script or repo regards it.

**Comment by davidkhess** [comment]
Good question. There is a bower.json file at the top of the repo on the 1.0 branch, but I don't see it on the 2.0 branch. Yet Vue 2.0 is available in bower.

**Comment by miljan-aleksic** [comment]
If there is a way to automate it, I have no problem on adding the script. But so far, no clue on how is done with Vue2.

**Comment by davidkhess** [comment]
Even thought the bower spec says a repo has to have a bower.json file, I'm beginning to think it is actually optional. So, maybe all you need to do is register the repo:

https://bower.io/docs/creating-packages/#register

**Comment by miljan-aleksic** [comment]
Done, try it please :)

**Comment by davidkhess** [comment]
Success!

```bash
$ bower install vuikit
bower vuikit#*              not-cached https://github.com/vuikit/vuikit.git#*
bower vuikit#*                 resolve https://github.com/vuikit/vuikit.git#*
bower vuikit#*                checkout 0.6.0
bower vuikit#*                resolved https://github.com/vuikit/vuikit.git#0.6.0
bower vuikit#^0.6.0            install vuikit#0.6.0

vuikit#0.6.0 ../bower/vuikit
$ 
```

Thanks!

**Comment by miljan-aleksic** [comment]
No problem :)
