### ISSUE TITLE
Other components

### ISSUE THREAD

**Issue by juppdes** [vuikit/vuikit#32]
They are working on creating other components? As Input, Radio, Select, Tooltip, etc ?

**Comment by miljan-aleksic** [comment]
We are working on Tooltip and there are some intentions about Notify, it depends on our current projects needs. Which one would you like to see next?

**Comment by kkinder** [comment]
+1 for tooltip. ;)

**Comment by miljan-aleksic** [comment]
@kkinder, both Tooltip and Notify are going to be part of the next UIkit3 compatible release :)
