### ISSUE TITLE
Codepen Playground

### ISSUE THREAD

**Issue by fabiandev** [vuikit/vuikit#34]
The codepen playground doesn't seem to work, so I set up a JSFiddle to play around with vuikit:

[https://jsfiddle.net/fabiandev/cuz6qs43/](https://jsfiddle.net/fabiandev/cuz6qs43/)

Feel free to fork, and thanks for this great package :)

**Comment by miljan-aleksic** [comment]
You are welcome @fabiandev :)

We have updated the pen with latest changes. Now should work. Thanks!
