### ISSUE TITLE
Filter-Control from 0.5

### ISSUE THREAD

**Issue by dschniepp** [vuikit/vuikit#35]
What happened to the Filter-Control from 0.5, was it removed accidentally?

https://github.com/vuikit/vuikit/blob/0.5/src/views/Filter.vue

Btw. I really enjoy your work, thank you!

**Comment by miljan-aleksic** [comment]
Hi! It has been removed in order to keep the main components as simple and reusable as possible. The Filter was an interesting experiment which will be most likely relaunched as part of another Vuikit set. I have updated the changelog.

I'm glad to hear that, I also enjoy working on it :)

**Comment by dschniepp** [comment]
Do you have any timeline for the more advanced components?

**Comment by miljan-aleksic** [comment]
We have started a migration of our projects toward Vuikit and the result of it may result in a new set of components, but is too soon to say anything.
