### ISSUE TITLE
Including UIKit

### ISSUE THREAD

**Issue by Christilut** [vuikit/vuikit#37]
Hey, just wondering what the best way is to include uikit itself to a webpack project.

Using a fresh webpack project generated with `vue-cli webpack` and I can confirm that vuikit works but uikit CSS/JS is not working.

I added uikit with `yarn install uikit` but I'm not sure how to make webpack load the correct files. Simple `require('uikit')` didn't work for me.

**Comment by miljan-aleksic** [comment]
You don't need any UIkit js files, so there is nothing to import from npm. Just load your UIkit css theme in your project. If you want the theme files build with webpack one way is importing the uikit.less file into the main App component vue file.

**Comment by Christilut** [comment]
I know this is more of a webpack config problem but can you show me an example of how you import the uikit styles? I can't get it to work.

**Comment by miljan-aleksic** [comment]
Sorry, was busy to answer earlier. Thanks to vue-loader you could do something like:

```html
<style lang="less">
  @import "myUikitTheme/uikit.less";
</style>
```

And in the webpack config:

```js
plugins: [
  // extract css into its own file
  new ExtractTextPlugin(...)
]
```

Check vue-cli webpack template for more details about this approach.

**Comment by Christilut** [comment]
Thanks, got it working.

For anyone having trouble with this, I did the following:

`npm install less less-loader`

in App.vue:
```
<style lang="less">
  @import '~uikit/themes/almost-flat/uikit.less';
  @icon-font-path: '../../fonts';
</style>
```

Font path was wrong so had to change that.
