### ISSUE TITLE
Datepicker dropdown position

### ISSUE THREAD

**Issue by kamil-borkowski** [vuikit/vuikit#38]
Hi!

It seems that there's no way to change Datepicker's dropdown `position`. The prop in there always falls back to default `"bottom left"`. Does anyone know a way to deal with this problem?

Thanks!

**Comment by miljan-aleksic** [comment]
Can you provide a codepen or jsfiddle reproducing this issue? Make sure using latest version.

**Comment by kamil-borkowski** [comment]
Sorry for not responding right away, I was away for some time. Anyway, here's the example:
http://codepen.io/anon/pen/MbearW

I added `:position="'bottom right'"`, but it doesn't matter, as `vk-datepicker-drop` does not accept `position` prop. Is there a way to make the dropdown appear to the left of input?

**Comment by miljan-aleksic** [comment]
Hi @kamil-borkowski,

you are right, that option is missing. The DatepickerDrop is a simple wrapper between VkDropper and VkDatepicker, as a quick solution you could copy and improve it adding the missing `position` prop. If you need help with that, let me know.

In the next release will see to fix that, anyway.

**Comment by kamil-borkowski** [comment]
Thanks for the quick response @miljan-aleksic! Understood, I think I'll mange from now on.

Also, thank you for your effort in making vuikit, I appreciate it a lot, keep up the good work guys! ✋
