### ISSUE TITLE
vk-modal modal not showing

### ISSUE THREAD

**Issue by shershen08** [vuikit/vuikit#42]
I am using the code from the official documentation - https://vuikit.github.io/vuikit/#/modal
```
<vk-button @click.native="show = true">
  Open
</vk-button>
<vk-modal :show="show"
  @clickOut="show = false"
  @inactive="show = false"
  @keyEsc="show = false">
  <a class="uk-close"
    @click="show = false">
  </a>
  <div class="uk-modal-header">
    <h2>Headline</h2>
  </div>
  <p>Lorem ipsum...</p>
  <div class="uk-modal-footer">
    Footer
  </div>
  <div class="uk-modal-caption">Caption</div>
</vk-modal>
```
The modal - it's just not showing. However the html is transformed correctly.

Here's a codepen with vk-modal (not working) along with some other elements from the vuikit that work just fine: http://codepen.io/shershen08/pen/oYWvwo?editors=1010 

vue.js - 2.0.3
moment.js - 2.15.1
uikit.css - 2.27.1

**Comment by miljan-aleksic** [comment]
The default or custom UIkit themes will not work out of a box for some components as described in https://github.com/vuikit/vuikit#custom-uikit-themes. Use the Vuikit theme or adapt yours following those instructions.

**Comment by shershen08** [comment]
Sorry, I've missed this part.
You could maybe specify in more detail where those ```.hook-modal , .hook-modal-dialog``` could be applied. But at leat including the ref to your ```http://vuikit.github.io/vuikit/static/css/vuikit.css``` made the demo work.

**Comment by miljan-aleksic** [comment]
Readme updated with some more information about custom themes ;)
