### ISSUE TITLE
Missing tether ?

### ISSUE THREAD

**Issue by cgarnier** [vuikit/vuikit#43]
Hello,
I got this exeption with the date picker dropdown.
It trying to use an undefined instance of tether.
I cant find any reference to tether in deps.

`vuikit.common.js?09d2:2422 Uncaught (in promise) TypeError: Cannot read property 'enable' of undefined(…)(anonymous function) @ vuikit.common.js?09d2:2422func `

**Comment by miljan-aleksic** [comment]
Hi again :)

In the dev we have changed Tether for Popper. Will be releasing a new version soon, but if interested in trying it out now, just build the dev version and install the local version. Exg. `npm i /myrepos/vuikit`.

**Comment by miljan-aleksic** [comment]
I'm not able to reproduce it, though. The Tether is listed as dev dependency as it is imported in the core code during the build.
