### ISSUE TITLE
target by id

### ISSUE THREAD

**Issue by cgarnier** [vuikit/vuikit#44]
Hello,
You should avoid to target with the html ids. 
It s not a good vuejs aproche.
Prefer refs.

**Comment by miljan-aleksic** [comment]
Hi! I agree, but in Vue 2 refs are not available when the component is being inited. An alterntaive could be to pass the ref as string on the target prop, deprecating the queries.

**Comment by miljan-aleksic** [comment]
Closing this one as it has been addressed in next branch.
