### ISSUE TITLE
Style doesn't apply on table component

### ISSUE THREAD

**Issue by webgodo** [vuikit/vuikit#45]
I have imported library in my `webpack` project with following line:
`import Vuikit from 'vuikit'`

and this is where I've included a `table` in my `template`:
```
<vk-table v-show="tableRows.length"
              selectable
              condensed
              hover
              trackBy="id"
              :fields="table.fields"
              :rows="tableRows">
    </vk-table>
```

It is working fine and viewing data properly, but it has no style applied. I mean it doesn't have the theme which is in your Demo.
![asd](https://cloud.githubusercontent.com/assets/3098974/20919157/a311edd2-bbaf-11e6-9dc0-32674bebfa87.png)

**Comment by miljan-aleksic** [comment]
Hi, you must load the styles on your project specifically by using the [vuikit-theme](https://github.com/vuikit/vuikit-theme) or a custom UIkit theme (read the readme in this case). Webpack doesn't, and can't, deal with that, so just make sure to include the theme CSS as you consider better for your project.

**Comment by webgodo** [comment]
Tnx, it did work
