### ISSUE TITLE
How to render buttons and HTML in columns

### ISSUE THREAD

**Issue by webgodo** [vuikit/vuikit#46]
Hi, thanks for your nice components

I've loaded and showing data in `Table` component properly, but in every row I have fields like `isActive` and an `action` column. I want to place `HTML` in those fields. How can it be achieved?

**Comment by miljan-aleksic** [comment]
You are welcome :)

In the fields configuration you can pass a render function for each column. The function will receive the row and field as props. It should look something like this (assuming you are using build from dev branch):

```js
fields: [{
  render (h, { props }) {
    const { row, field } = props
    return h('div', ...)
  }
}]
```
