### ISSUE TITLE
incorrect day of week - datepicker component

### ISSUE THREAD

**Issue by yu1222** [vuikit/vuikit#48]
Hi,

![datepicker_bug](https://cloud.githubusercontent.com/assets/6902359/21177011/a6f846fc-c22c-11e6-8b17-3546c664db2b.JPG)

The above image is the capture of the official documentation (http://vuikit.github.io/vuikit/#/datepicker)

January 1, 2017 is not Saturday.
I think it is bug. Plz fix it! 😫
or.. how can i change locale of moment for datepicker components?

(+)
uikit 
![uikit_datepicker](https://cloud.githubusercontent.com/assets/6902359/21177477/b62a4970-c22e-11e6-8ec1-fb031b293135.JPG)
The above image is the capture of the uikit documentation (https://getuikit.com/docs/datepicker.html)
it's correct.

**Comment by miljan-aleksic** [comment]
Embarrassing, lol. I will have to add more unit tests there... Anyway, will be checking this out soon and let you know.

**Comment by miljan-aleksic** [comment]
The issue has been fixed with 0.6.1 release ;)
