### ISSUE TITLE
datepicker component bug

### ISSUE THREAD

**Issue by yu1222** [vuikit/vuikit#52]
Hi, again

I think you wrote wrong round brackets in this code ([Datepicker/index.js#L51-L56](https://github.com/vuikit/vuikit/blob/e774622/src/lib/Datepicker/index.js#L51-L56))
If `disabledDatesMoments` is empty, then `min` ,`max` props are useless..
it should be changed as shown below.
```
isDisabled (date) {
    return !date.isBetween(this.minMoment, this.maxMoment) ||
        this.disabledDatesMoments.some(d =>
            d.format("YYYY-MM-DD") === date.format("YYYY-MM-DD")
        );
}
```

And one more,
`prevMonth` ,`nextMonth` compare logic is little bit strange..
[Calendar/index.js#L77-L82](https://github.com/vuikit/vuikit/blob/e774622c438d7c1cff0540aca5e1981866e18f13/src/lib/Calendar/index.js#L77-L82)

For example, If `min` == `2016-12-21` and select `2017-01-21`, then.. i can't go December 2016.
so, i can't select `2016-12-24`. :tired_face:

![vuikit_calendar](https://cloud.githubusercontent.com/assets/6902359/21398842/54560234-c7ec-11e6-97fb-b45aff682aa5.PNG)
I think `prevMonth`, `nextMonth` should have just "month", not include "date"..

Please check the issue~
Thanks!

**Comment by miljan-aleksic** [comment]
Hi! Thank you for your report!

Disabled dates evaluation issue confirmed and solution accepted. As for the second issue, I can't reproduce it, could you create a codepen or jsfiddle?

I agree, next/prev month could be just a ISO `YYYY-MM` string but a Moment.js is expected everywhere. In the next branch, though data-fns is used instead and the change didn't break anything, so I will do apply there that change.

**Comment by yu1222** [comment]
http://codepen.io/anon/pen/KNYEXv?editors=1111
please see just code.. actually it's not working in codepen..(because module import failed...)  :(
In fact, i make `CustomDatepicker`, it extends using `Datepicker`. 
And **add props(`locale`, `min`, `max`).**
Thank you!

**Comment by miljan-aleksic** [comment]
Please make an example where the standard components are used and don't try to fix the issues, just expose them.

**Comment by yu1222** [comment]
ok. I see.
