### ISSUE TITLE
How to install and use

### ISSUE THREAD

**Issue by muminoff** [vuikit/vuikit#53]
Hey guys. Sorry if my question seems too stupid. Honestly, I am new to Vue.js and I know my question may not be releveant to this project. I followed official Vue.js tutorial and had learned basic stuff. After looking for good UI kits which are based on Vue.js, I have come to decision to use your project. I followed your documentation, installed via npm and included in `main.js`. But, I never can get components rendered correctly. For example, if I use `<vk-button>` in my template, it is being rendered as standard button.

Can you guys provide me very simple boilerplate based on `vue-cli` which can be generated with`$ vue init webpack mysample`?

Edit: grammar

**Comment by miljan-aleksic** [comment]
Hi Sardor! That seems a good idea, so I went ahead and created a vue-cli template based on the official webpack-simple. You can check it out at https://github.com/vuikit/vue-cli-vuikit-webpack.

Let me know if that helped! :)

**Comment by muminoff** [comment]
Hello Miljan. Thanks so much for your quick response. I checked out the template you have created for me and this is awesome.

If you don't mind I have one more question. How can I get same CSS style which is from https://vuikit.js.org?

Do I need to include `vuikit.css` in `index.html`? Or am I missing any other step here?

I am attaching screenshots for your convinience.

This style is from https://vuikit.js.org
![image](https://cloud.githubusercontent.com/assets/1235454/21465105/ccc792c2-c9d7-11e6-8e4a-ef6381ffc43e.png)

This one is from the template you have just created.
![image](https://cloud.githubusercontent.com/assets/1235454/21465106/f8bfc660-c9d7-11e6-94e6-f4f648c7a5a0.png)

Thanks in advance.

**Comment by muminoff** [comment]
Update:

Yes, I think, I needed to include `vuikit.css` to get the same style from the homepage. Honestly, I chose `vuikit` because of it's style. I really liked it.

Great job @miljan-aleksic ! Thanks again.

![image](https://cloud.githubusercontent.com/assets/1235454/21465121/e64822ec-c9d8-11e6-8b9a-50477c0980ee.png)

**Comment by miljan-aleksic** [comment]
Yes, you got it :)

The [Vuikit Theme](https://github.com/vuikit/vuikit-theme) is an UIkit customized theme inspired by the Pagekit admin one. You can customize it further following UIkit docs or just include it in your project as it is.

**Comment by ghprod** [comment]
Any chance to include `theme.less` instead `dist/vuikit.css` ?

I've tried but got so many error can't resolve file .. :(

**Comment by miljan-aleksic** [comment]
You can require any published file, example `require('vuikit/src/theme.less')`. Open a new ticket if you need further help.

**Comment by bretonio** [comment]
Blessed be the creators of excellent boilerplate and may their projects always prosper. Many thanks.
