### ISSUE TITLE
Scrollable or swipable tabs heads

### ISSUE THREAD

**Issue by zapping** [vuikit/vuikit#56]
Hi,
 I was trying the tabs. When you have a lot of tabs that does not fit into the page they wrap down to the next like. Instead of this can the tab heads be made scrollable like the tabs of a browser or swipable on mobile.

Thx.

**Comment by miljan-aleksic** [comment]
Hi, the way UIkit deals with it is combining the [Tabs into a dropdown](https://getuikit.com/v2/docs/tab.html#tabs-with-dropdowns). That seems doable, will check it out.

**Comment by zapping** [comment]
Drop down is good. But if it is swipable on mobile then I think it will be cool as it seems more natural and then there won't be the additional screen that comes on when you touch the drop down.

**Comment by miljan-aleksic** [comment]
To limit the amount of custom CSS we must keep with UIkit approach. Meaning, this last suggestion should be addressed to UIkit instead :)
