### ISSUE TITLE
UIkit 3?

### ISSUE THREAD

**Issue by jerry1970** [vuikit/vuikit#57]
What will happen with/to vuikit and what will developers notice or have to do when UIkit is moving to their version 3?

**Comment by miljan-aleksic** [comment]
Vuikit in next branch is already UIkit3 compatible, although is not yet recommended for production. Developers would have to adapt their code to the new API, in general small changes. There is no ETA for the release, but we are working actively on it.

**Comment by jerry1970** [comment]
Cheers, thanks for the update. I know UIkit 3 is not ready for production and that developers need to change their code but as long as vuikit is coming along with v3 I will keep exploring vuikit.

**Comment by miljan-aleksic** [comment]
Yep, you can count on Vuikit being actively developed and compatible with latest UIkit code.

**Comment by israrwz** [comment]
Great job vuikit team !

I'm eagerly waiting for the uikit3 compaitable release.

**Comment by miljan-aleksic** [comment]
Thanks @israrwz, we are getting there :)

**Comment by michaelrtm** [comment]
have you already updated docs for the new changes, or will you be waiting for an official release?

**Comment by miljan-aleksic** [comment]
Yes, the docs would be rewritten after the refactoring. I am finishing the App that is being built with it and while doing so many real use case issues are solved. Very happy with the results so the stable release is getting closer.
