### ISSUE TITLE
export 'default' (imported as 'Vuikit') was not found in 'vuikit'

### ISSUE THREAD

**Issue by danderozier** [vuikit/vuikit#60]
This issue occurs on the `next` branch implementing UiKit 3.

## Overview
To replicate:

1. Start an empty Vue project using `vue init webpack project`
2. Install Vuikit via `yarn add https://github.com/vuikit/vuikit#next`
3. In main.js, add
```
import Vuikit from 'vuikit'
Vue.use(Vuikit)
```
4. Start dev server with `npm run dev`.

## Expected behavior
The Vue project should load without errors.

## Actual behavior
The dev server gives this warning:
```
warning  in ./src/main.js

7:8-14 "export 'default' (imported as 'Vuikit') was not found in 'vuikit'
```
And the browser's js console displays the error:
```
Uncaught TypeError: Cannot read property 'installed' of undefined
    at Function.Vue.use (eval at <anonymous> (app.js:723), <anonymous>:3443:15)
    at eval (eval at <anonymous> (app.js:778), <anonymous>:14:45)
    at Object.<anonymous> (app.js:778)
    at __webpack_require__ (app.js:660)
    at fn (app.js:84)
    at Object.<anonymous> (app.js:964)
    at __webpack_require__ (app.js:660)
    at app.js:709
    at app.js:712
```

**Comment by miljan-aleksic** [comment]
Thanks @danderozier, will be checking this asap.

**Comment by miljan-aleksic** [comment]
@danderozier, please try again now.

**Comment by danderozier** [comment]
It's working now!
