### ISSUE TITLE
Some issues with the datepicker-drop

### ISSUE THREAD

**Issue by brandonn1231** [vuikit/vuikit#61]
Hi, thanks for creating these awesome vue components.  However, I've been having some issues with the "vk-datepicker-drop" component.
1) When I click on the input field to generate the dropdown calendar, the calendar pops up above the input field, unless I shrink the page to a smaller width (I need it to always appear below the input field).
2) When I click on the "next" arrow to change the month, the month doesn't change unless I click out of the dropdown and then click back in.
3) Is it possible to make it so the dropdown calendar automatically minimizes after choosing a date?  Right now I have to click outside to make the dropdown go away.

I'm using the vuikit cli that you created.  Thank you for the help!

**Comment by miljan-aleksic** [comment]
Hi there!

I would suggest you to skip using the DatepickerDrop and create your own combination, as it will be deprecated in next release.

Check the datepicker-drop as example to create your own version and there adjust the dropdown features to work as you expect.

1. That should be adjustable in the popper settings.
2. That seems working ok in the demo. Are you getting any js issues?
3. Yes, now that you are gonna create your own wrapper :)

If you still have issues create a jsfiddle with your code so far and will help you out.

**Comment by brandonn1231** [comment]
Ah ok, thanks for the advice.  I was wondering if you could also point me in the right direction when using buttons (and the checkboxes, which I guess is just an extension of buttons).  I added the vk-button tags to my component, but when I click on them, the buttons dont get selected/highlighted.  Do I need to write my own method that does this? (I just copied the sample code from your site and pasted it into the vuikit cli components)

**Comment by miljan-aleksic** [comment]
Sure, just open a new ticket and point there a jsfiddle or codepen with your buttons configuration.
