### ISSUE TITLE
Not full port? Scroll/sticky/parallax is present?

### ISSUE THREAD

**Issue by kodeJ** [vuikit/vuikit#63]
Hi guys. Recently discovered UIKit, but was frustrated since it's using jQuery. Then I found you, but frustrated once again, since I can't find all UIKit components, that I needed in first place:

Animation
Grid parallax
Parallax
Scroll
Scrollspy
Sticky

Is there any specific issues/reasons why you can't implement them? Or may be it's in plans?

**Comment by miljan-aleksic** [comment]
Hi @kodeJ, we are porting what we need/use in our projects. Beside Sticky, which is on the list, the rest is currently not planned.

**Comment by kodeJ** [comment]
Ok. Well, proper sticky implementation also nice. Hope it will be compatible with SSR, since other Vue-sticky packages are not (at least I wasn't able to load them).
