### ISSUE TITLE
UIKit Lightbox close button not working properly in presence of VUIkit CSS

### ISSUE THREAD

**Issue by davidkhess** [vuikit/vuikit#64]
It looks like the VUIkit CSS for the modal transitions is breaking the regular UIKit Lightbox because it uses a normal modal under the covers.

With the changes by VUIKit to the transition CSS for modals, a CSS transition event that is assumed to happen on a normal modal is not firing. As a result, the close button doesn't work properly because it's trying to hook onto this transition event that is not firing (but does fire later after some other transition occurs).

To recreate:

* Set up VUIkit.
* Set up a Lightbox per UIkit documentation with a group (two images).
* Trigger the lightbox.
* Click the close button - nothing happens.
* Navigate to the second image.
* After the second image loads/animates in, the lightbox closes.

Would it be possible to get some native support for Lightboxes in VUIkit? Or barring that, could we get some CSS for the modal transitions that doesn't interfere with the operation of the stock Lightbox component from UIkit?

**Comment by miljan-aleksic** [comment]
Thanks for the feedback @davidkhess. Using Vuikit in combination with UIkit was never the goal, thus those compatibility tests were ignored. Anyway, Vuikit next version will rely entirely on UIkit default CSS and that kind of issues should be gone. Meantime, the only solution I could think of is to create a separate UIkit theme with a different prefix, or use UIkit Modal instead.

Note that Vuikit next is being deeply refactored, it will take some time to get a public release ready.

**Comment by davidkhess** [comment]
Thanks for the info. The plans for the next version sound good - since VUIkit is just a subset of what's possible with UIkit, it makes it harder to justify using it if it means the rest of UIKit becomes unsupported – and possibly broken. It sounds like that will not be the case with the next version.

I ended up lucky in this case and could remove VUIkit from the page in question.
