### ISSUE TITLE
Documentation about the use of datepicker dropdown?

### ISSUE THREAD

**Issue by mdeprezzo** [vuikit/vuikit#65]
Hi all,
i don't see any documentation, on how to use datepicker with this package ? Where can i find some info ?

**Comment by miljan-aleksic** [comment]
Hi, in the site Datepicker section there is an example of a Dropdown integration with Datepicker - https://vuikit.js.org/#/datepicker

**Comment by mdeprezzo** [comment]
I see, but doesn't works. I register globally Vuekit, and i've past and copy the example. But anyway i don't see the datepicker on input focus

**Comment by miljan-aleksic** [comment]
Create a JS fiddle and provide it url, please.

**Comment by mdeprezzo** [comment]
I've found the issue. I'm using this component with a template, based on uikit. And there are some css class that i need to modify, in order to see the datepicker component. So, i think that i can modify the class using `:class` attribute right ?

**Comment by miljan-aleksic** [comment]
Checkout the readme about that, you must create a custom UIkit theme.
