### ISSUE TITLE
Responsive tabs

### ISSUE THREAD

**Issue by vadimpopa** [vuikit/vuikit#66]
I don't think at this moment in vuikit it's possible to have responsive tabs without uikit. Any plans to add this feature to the tabs ?

<img width="273" alt="screen shot 2017-07-26 at 12 28 45 pm" src="https://user-images.githubusercontent.com/3592131/28614335-1fc200b0-71fe-11e7-9912-8505a4ae2979.png">

**Comment by miljan-aleksic** [comment]
Seems more a combination of two components to solve a specific situation than an integral part of Tabs. For the moment there are no plans for implementing it.
