### ISSUE TITLE
IE - Calendar Selector not working 

### ISSUE THREAD

**Issue by ohute-couture** [vuikit/vuikit#67]
## IE - Calendar Selector not working 

Hi, Report a bug
Changing the year / date in calendar causes an error in IE
This is due to `event.target.selectedOptions` IE Bug
[event.target.selectedOptions IE Bug](https://github.com/facebook/react/issues/5791)
please, Modify to use `event.target.value` instead of `event.target.selectedOptions`

I tested it using `event.target.value` and it worked fine.

**Comment by miljan-aleksic** [comment]
Thank you for the report, will be checking this out asap.

**Comment by ohute-couture** [comment]
When will it be fixed?
We need this  asap
