### ISSUE TITLE
Vuikit and styling

### ISSUE THREAD

**Issue by Nickvda** [vuikit/vuikit#69]
Greetings!

I like what I'm seeing with Vuikit, I just can't seem to find the styling. From other issues I've seen that I should import .less/scss files, but those do not come with the package, which leaves me wondering about what's going on.

So what is the preferred way of going about this? Thanks in advance :-)

**Comment by miljan-aleksic** [comment]
Hi!

As Vuikit is based on UIkit all you have to do is load a UIkit theme. We provide one at the [Vuikit Theme repo](https://github.com/vuikit/vuikit-theme) which already solves some edge issues explained in the Readme, but you can also [create your own](https://getuikit.com/v2/docs/documentation_create-a-theme.html).

Take in mind that Vuikit is based on UIkit 2.

**Comment by Nickvda** [comment]
Ah thanks, that seems to be the missing link.. Thanks :)

**Comment by miljan-aleksic** [comment]
Well, is not a dependency, but I have updated the readme hoping it's more clear now.
