### ISSUE TITLE
Vuikit Next modal body

### ISSUE THREAD

**Issue by HDsign** [vuikit/vuikit#70]
https://github.com/vuikit/vuikit/blob/38db950e32a32c13cc90acc4abd164f99d56bdd5/src/components/modal/modal.vue#L45

With the main slot already in the uk-modal-body
you can't easily put something in de dialog itself.
We I was kinda using this in some of my designs.
Perhaps some properties with `body-class` or something?

**Comment by miljan-aleksic** [comment]
What about adding a `dialog` slot? It should solve many edge situations.

**Comment by HDsign** [comment]
That seems like a good solution 👍
