### ISSUE TITLE
@vuikit/vuikit removed from NPM

### ISSUE THREAD

**Issue by HDsign** [vuikit/vuikit#71]
Hello just realized the @vuikit/vuikit package was removed from npm.
What is reason and how to work around this?

**Comment by miljan-aleksic** [comment]
Hi! Sorry about that, I am cleaning it all up for the next 0.7.0 release. You can install it already using the @next tag. Eg. `npm install vuikit@next`.

There were some internal changes but should be easier now. Check the info at https://github.com/vuikit/vuikit/tree/next/packages/vuikit.

If there is anything misleading, let me know!

**Comment by HDsign** [comment]
Okay thank you!
