### ISSUE TITLE
Scrollspy and ScrollspyNav component

### ISSUE THREAD

**Issue by Al-Rozhkov** [vuikit/vuikit#72]
Hi @miljan-aleksic! Thank you for your awesome work with vuikit!

Recently you have added Scroll component. It would be great to have Scrollspy component too. Do you plan to implement it?

**Comment by miljan-aleksic** [comment]
Yes @Al-Rozhkov, I have already started its implementation :)

**Comment by miljan-aleksic** [comment]
Its commited ;)
