### ISSUE TITLE
The documentation page has error

### ISSUE THREAD

**Issue by liphvf** [vuikit/vuikit#77]
![screenshot-2018-3-16 vuikit](https://user-images.githubusercontent.com/2036030/37538358-291eb3d6-292f-11e8-9a73-a2dbe1aa806a.png)
The documentation page has error. Image above:
URL: https://vuikit.js.org/guide/navbar/
Browser: Firefox 59

**Comment by joeinnes** [comment]
I have 'Cannot read property '$on' of undefined'

**Comment by miljan-aleksic** [comment]
It's a bug in the VkNavbarDropbar, I am working on the solution. Thanks both for mentioning it.

**Comment by miljan-aleksic** [comment]
The documentation is working now and the next Vuikit release will solve Dropbar issue. Thanks again.
