### ISSUE TITLE
Update documentation to show what imports are required for each component

### ISSUE THREAD

**Issue by mjbates7** [vuikit/vuikit#81]
Hi,

I think it would be useful and more explicit if in the documentation, it told you what imports to use for that particular component.

For example to use a [card](https://vuikit.js.org/guide/card) and a button/button link, put a heading such as "Required Imports:" on the page?
```
import { Card } from 'vuikit/lib/card'
import { Button, ButtonLink } from 'vuikit/lib/button'
```
Thoughts?

**Comment by miljan-aleksic** [comment]
Thank you for your feedback @mjbates7, it's always appreciated.

Each component requires only one import, the component itself. It is the demos that could require an additional one, but those are optional as you could use a native button for example.

Stating the imports on each demo code would make more sense, but assuming the newcomers followed the integration guide and imported the whole library while testing, it would not be of much help to them.

As for advanced users trying to lower their bundle size, it is expected they know what components are used in their project and again, the demo imports statements would be of no much help.

Anyway, those are my thoughts, let me know if I am missing something.
