### ISSUE TITLE
Missing vuikit.css

### ISSUE THREAD

**Issue by michaeljaekel** [vuikit/vuikit#82]
Hi,

I'm a beginner to vuikit (and also quite new to vue).
I tried to use vuikit via build tools. So I did

```
install vue-cli
$ npm install --global vue-cli
$ vue init webpack my-project
$ cd my-project
npm install vue
npm install vuikit
npm install @vuikit/icons
```
 After solving a missing depency for vuikit (npm -i ajv) I started

`$ npm run dev`

without any errors. 
But the components are not rendered as expected. They where just plain HTML and a vk-button rendered as a normal button.
So I tested a lot until i found that there isn't any vuikit.css in my node_moduls/vuikit/dist/folder. 
I downloaded the complete vuikit.zip and copied vuikit.css to node_moduls/vuikit/dist/.
After that I have to import the css file in main.js with 
`import 'vuikit/dist/vuikit.css';`

Now the component are designed as expected. Did I miss something in your documentation for a more easier setup? If not, could you please update the docs? May be, it would be fine if the npm package includes a vuekit.css

Best
Michael

**Comment by miljan-aleksic** [comment]
Hi Michael,

you are right, the guide expects you to provide your own theme but for newcomers and/or quick setup would be wise to include the default theme. The theme has recently been separated into it own module, `npm i @vuikit/theme` and then replace the import with `import '@vuikit/theme'`.

I will update the guide asap, thank you for your feedback.

**Comment by michaeljaekel** [comment]
Hi Miljan,

thanks for your support!
I changed my setup to use the module via npm. Works fine!

**Comment by miljan-aleksic** [comment]
Guide updated ;)

**Comment by michaeljaekel** [comment]
Great!

**Comment by michaeljaekel** [comment]
Hi Miljan, 

Since this is a little bit offtopic, I'm just appending it to this issue (leaving it closed).
Seems, there is something wrong with your website's title tag generator.
Instead of pointing out to vuikit the title of the website is "undefined is not a function" (search results for "vuikit" on google

May be, you would like to fix this to have better rankings and could be find more easier by beginner like me...

[https://www.google.de/search?ei=Tqu_Wpv1GMLsUpTeh7gP&q=vuikit&oq=vuikit&](url)

**Comment by miljan-aleksic** [comment]
The website code seems ok, perhaps is a cache issue from the previous site. Will investigate further during next week. Thanks for pointing it out.
