### ISSUE TITLE
Dropdown Orientation

### ISSUE THREAD

**Issue by bretonio** [vuikit/vuikit#83]
I have a simple issue possibly already covered [here](https://github.com/vuikit/vuikit/issues/30).
My dropdown drops down horizontally rather than the default vertically.

I am having a look at the documents for `Drop` as suggested. 

I have tried setting `mode` to `click` and `position` on `vk-dropdown` to something vertical for example. I set `mode="click"` with success for example. Set `position` has no effect.

I have tried importing the `uikit` &mdash; without the `v` &mdash; stylesheet following your suggestions in the issue cited above. Tried direct reference to the local version in `node_modules` as well as importing it in `main.js` of my Vue template as follows.

```
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import router from './router'

import Vuikit from 'vuikit'
import VuikitIcons from '@vuikit/icons'
import '@vuikit/theme'
import 'uikit/dist/css/uikit.min.css'
import UiKit from 'uikit'

Vue.use(Vuikit)
Vue.use(VuikitIcons)
```

And so on. My HTML follows the «Nav in Dropdown» snippet in your docs and looks like this.

```

    <div class="vk-inline">
      <vk-button type="default" size="large"><i class="material-icons">local_bar  </i>&nbsp;Drop Down Tonight</vk-button>
      <vk-dropdown position: top-center mode='click'>
        <vk-nav-dropdown>
          <vk-nav-item title="Monkeys" active></vk-nav-item>
          <vk-nav-item title="Gazelles"></vk-nav-item>
          <vk-nav-item  title="Lions"></vk-nav-item>
          <vk-nav-item title="Jackals"></vk-nav-item>
          <vk-nav-item title="Warthogs"></vk-nav-item>
          <vk-nav-item>Water Buffalo</vk-nav-item>
          <vk-nav-item title="Rhinoceros"></vk-nav-item>
        </vk-nav-dropdown>
      </vk-dropdown>

```

Having initial difficulty with modal and offcanvas as well but one thing at a time. Thanks hope I am not abusing your kind attention.

**Comment by miljan-aleksic** [comment]
Hi @bretonio, in Vuikit 0.8 and above there is no need for any CSS workarounds, your UIkit 3 theme will just work out of a box. If you don't have your own theme, you can use the Vuikit default one (without importing any UIkit styles).

As per the snippet, it has a lot of invalid vue syntax. I have fixed those and created a working [codepen](https://codepen.io/miljan/pen/vRzNmJ). Fork it, adapt it, and let me know if you need further help.

**Comment by bretonio** [comment]
You are more than kind!

cbrayton

**Comment by miljan-aleksic** [comment]
No problem :)

**Comment by bretonio** [comment]
What fixed it for me was simply removing the optional `<div class="vk-inline"> as a wrapper for the dropdown.

Again thanks for kind assistance.

cb

**Comment by miljan-aleksic** [comment]
@bretonio, what do you mean? Do you have any feedback on how could we improve the component or the documentation?

**Comment by bretonio** [comment]
Sorry if I was abrupt! I was a little confused when the VUIKit docs cited
tags with uk prefixes here and there. On the whole the docs are very
helpful however. Perhaps a CDN setup might be welcomed by some users. Keep
up the excellent work I actually find the Vue framework easier to grok than
the original.

cb

**Comment by miljan-aleksic** [comment]
UIkit takes cares of the layout and styling, while Vuikit of rendering it and executing the JS, as such both coexists. I will add some notes about that and avoid confusions with the prefixes.

As for the CDN, you can use the [cdnjs](https://cdnjs.com/libraries/vuikit) one. Will also update the docs about it.

Thanks for you feedback @bretonio.
