### ISSUE TITLE
Scroll offset

### ISSUE THREAD

**Issue by Aliba777** [vuikit/vuikit#86]
Hello! I am new to Vuikit and UIKit. Right now I have a problem with vk-button-link. I am using sticky-Navbar, so when I click on vk-button-link some information at the top is hidden (due to Navbar). I want to have offset, but I did not understand how to use offset. 

Could you make more clear guide how to use offset in the Scroll section, please? 

Thank you in advance!

**Comment by miljan-aleksic** [comment]
I will close the issue meantime.
