### ISSUE TITLE
uk-sticky in v0.6.3

### ISSUE THREAD

**Issue by AyushG3112** [vuikit/vuikit#87]
Hello, How can I use `data-uk-sticky` in v0.6.3?
Our UI uses a file    

``` html
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.4/js/components/sticky.min.js"></script>
```

to make some UIKit changes to the DOM, but I could not find anything in the v0.6.3 package

**Comment by miljan-aleksic** [comment]
Sticky is only available on Vuikit 0.8 and above.

**Comment by AyushG3112** [comment]
Got it, and turns out v0.8.2 is backward compatible, so using that now, cheers.

**Comment by miljan-aleksic** [comment]
Just take in consideration 0.6 is UIkit 2 based while 0.8 is UIkit 3.
