### ISSUE TITLE
`@vuikit/theme` does not get bundled during `npm run build`

### ISSUE THREAD

**Issue by AyushG3112** [vuikit/vuikit#88]
Hello.

I am using the following statement in `main.js` to globally load `vuikit` css.

``` javascript
import '@vuikit/theme';
```

While this works perfectly while `npm run serve`, in the production result of `npm run build`, the CSS is not loading.
However, there are other internal css files I'm loading in `main.js` such as:

``` javascript
import '@/assets/scss/base/colors.scss';
import '@/assets/css/core.css';
```

but they get bundled correctly.

**Comment by miljan-aleksic** [comment]
`import '@vuikit/theme';` references `@vuikit/theme/dist/vuikit.min.css` but perhaps that references fail on build. Try importing the referenced file directly.

BTW, what system are you using? Perhaps vue-cli 3?

**Comment by AyushG3112** [comment]
Yes, vue-cli 3 is what I use. And when I try importing the referenced file directly, `npm run serve` throws an error saying cannot find module.

**Comment by miljan-aleksic** [comment]
I just tested it and all the above works on server and on build. What versions of vuikit and vuikit/theme are being loaded?

**Comment by AyushG3112** [comment]
`@vuikit/theme` is `v0.8.0`
`@vuikit` is `v0.8.2`

I'll try debugging this again. 

One thing is, we're just getting started on our UI, so haven't included any `Vk*` components yet, just some `uk-*` classes on `div`s according to the layout our designer sent us.

So this might be tree shaking at work. I'll try adding some components and let you know.

**Comment by miljan-aleksic** [comment]
Tree shaking doesn't work that way. Check if the dist css file has any uk-* styles.

**Comment by miljan-aleksic** [comment]
I will close the issue meantime.
