### ISSUE TITLE
Complex example, with props.

### ISSUE THREAD

**Issue by ydennisy** [vuikit/vuikit#90]
Hello are there any guides for how to best pass props to `vk` components?

Also how to extend them?

Thanks!

**Comment by miljan-aleksic** [comment]
Hi there,

Vuikit components are standard Vue components, it inherits all best practices from Vue. You should review it [documentation](https://vuejs.org/v2/guide/components.html#Passing-Data-to-Child-Components-with-Props).

As for extending them, this is the [recommended way](https://vuikit.js.org/guide/components#extending-a-component), but not limited to.
