### ISSUE TITLE
How to add a link to a Vuikit table?

### ISSUE THREAD

**Issue by ydennisy** [vuikit/vuikit#91]
Hello!

I have tried literally everything to get this to work, and I am at the point of considering removing Vuikit...

I am simply trying to pass in some dynamic data to the component, and create a new HREF using the data whilst just displaying a LINK clickable text element :)

This is my table:
```
 <vk-table v-bind:data="paginatedData" narrowed>
            <vk-table-column-select></vk-table-column-select>
            <vk-table-column title="Vendor Name" cell="name"></vk-table-column>

            <vk-table-column title="Link">
                <a v-bind:href="policyUrl"></a>
            </vk-table-column>

            <vk-table-column title="Link2">
                <p cell="policyUrl"></p>
            </vk-table-column>

</vk-table>
```
The final two columns are left in to show some attempts I have made. The issue is that using Vuikit, the looping and using v-for is not available, so having to use the provided components...

**Comment by miljan-aleksic** [comment]
Hi Dennis,

altering the column rendering is done with slots, you can read the documentation about them [here](https://vuejs.org/v2/guide/components-slots.html) and check Vuikit guide with specific examples [here](https://vuikit.js.org/guide/table#slots). Additionally I have recreated your table example in [this pen](https://codepen.io/miljan/pen/GdGBbq).

I'm not sure what you mean by "using Vuikit, the looping and using v-for is not available". Those features are part of Vue core and cannot be removed or altered by Vuikit or any other library.

Let me know if you have further doubts.

**Comment by miljan-aleksic** [comment]
Vuikit Table does all the heavy rendering, so there is no need to use v-for, it does it for you based on the column definitions. If you are looking to create a raw html table, ignore that component and create raw html using UIkit classes, as detailed [here](https://getuikit.com/docs/table).

The doubts you are expressing are a lack of general Vue experience. I would suggest you to read the official docs and ask anything you don't understand about them in the Vue forums. For any Vuikit specific question, feel free to open a new ticket.

Also, please close [this](https://stackoverflow.com/questions/50317449/how-to-add-a-link-to-a-vuikit-vuejs-table) thread, as it just become redundant ;)
