### ISSUE TITLE
How to keep Vuikit CSS local to the app?

### ISSUE THREAD

**Issue by ydennisy** [vuikit/vuikit#95]
Hello,

I am using Vuikit, Vue + Webpack 4 to build an app which gets injected via a script tag onto a third party site.

The app is collecting CSS props from the host site.

Is there a way to ensure the CSS props neither are polluted by or pollute the parent page?

Thanks in advance!

**Comment by miljan-aleksic** [comment]
Probably the best you can do is precompile the styles and import the css file instead of less.

**Comment by ydennisy** [comment]
thanks @miljan-aleksic could you provide a little more information on how I could achieve this?

**Comment by miljan-aleksic** [comment]
If you are importing a less file it means you are creating your own UIkit theme and for such you should have in place a build task for it. Check [UIkit documentation](https://getuikit.com/docs/less#how-to-build) for details. You can also check [Vuikit Theme build](https://github.com/vuikit/vuikit/blob/master/packages/vuikit-theme/scripts/build.js#L8-L18) as example.

Once you have the build in place, just run it and import the resulting css in your project.

**Comment by ydennisy** [comment]
Hey @miljan-aleksic I am not important anything other than the standard theme, which I see contains both css and less files.

Am I correct to assume your package is already building them via the build script you shared?

One thing to note is when CSS is applied directly at the single file component level into scoped CSS - this issue does not exist.

is there a way to mimic such behaviour for the whole Vuikit package?

**Comment by miljan-aleksic** [comment]
Yes, the Vuikit Theme provides the css by default in dist. Use the the src files only when extending.

In such case you need to tell me more about `The app is collecting CSS props from the host site.`, as it not what I assumed.

**Comment by ydennisy** [comment]
Ok, so the app when loaded into the page, will inherit the fonts of the host webpage.

The app is being loaded as a script tag on a host page:
`<script src="https://myapp.com/bundle.js">`

The app itself is a Vukit Modal Element, which is mounted to the DOM in the normal Vuejs manner:
`const vm = new Vue(App).$mount('#app');`

The interference of styling happens both ways, i.e the app itself inherits fonts, whilst passing some CSS to the page. If you want to take a look like please visit http://wearemiq.com and add the following into your browser console:

```
const pluto = document.createElement('script');
pluto.setAttribute('id', 'pluto-cmp-js-src');
pluto.setAttribute('src', 'http://pluto-cmp.com/cmp');
pluto.setAttribute('client-id', '1');
document.body.appendChild(pluto);
```

Thank you for your help!

**Comment by miljan-aleksic** [comment]
Got it. That's a broader issue you will have to find the best way to deal with. One way is to use iframes, a site loaded in an iframe has a native browser scope.

Another way and it seems is the one you are looking for, is to scope the theme styles with a custom class. You can find more info and instructions [here](https://getuikit.com/docs/avoiding-conflicts#scope-mode). But I'm afraid there is no way to avoid the main site interfiering with UIkit styles, and you will have to do some manual resetings, adjustments.

**Comment by ydennisy** [comment]
Ok but there is no way to inject the Vuikit CSS into each single file vue component rather than having them float around in global scope?

**Comment by miljan-aleksic** [comment]
No, not that I am aware about. UIkit themes were not designed with that in mind, but they source code is modular and well structured, perhaps you can find a way to make it work.

**Comment by ydennisy** [comment]
Thanks again @miljan-aleksic - final Qs on this I promise:

- if I want to use uikit in scope mode how could I configure vuikit to this custom setting https://getuikit.com/docs/avoiding-conflicts#scope-mode
- also is it possible to exclude the base class which contains all the references to global CSS selectors such as html, h1 etc

**Comment by miljan-aleksic** [comment]
Vuikit doesn't apply any custom styles, it all relies on an standard UIkit theme, which Vuikit provides but doesn't impose.

- Meaning you can create your custom theme, scoped or not, and just load it instead the Vuikit one.
- Once the theme is scoped, all elements will be scoped, even the native html ones.

No problem, feel free to ask :)
