### ISSUE TITLE
CSS conflicts when using Vuikit with Uikit

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [vuikit/vuikit#99]
Hey there,

I have a project that was using Uikit by a lot of time. Now I'm implementing Vue.js in some sections of the system, but because Uikit CSS is already in use, and we have some custom rules, the Vuikit theme is causing conflicts.

Is there a way to use Vuikit without the theme, using the default Uikit CSS?

Thanks!

**Comment by miljan-aleksic** [comment]
Hi :)

Vuikit Theme is totally optional, just use your theme instead. Make sure it is based on the latest UIkit updates, though!

**Comment by TiagoSilvaPereira** [comment]
Thanks @miljan-aleksic , it is working very well!!

**Comment by miljan-aleksic** [comment]
Great! The only part that will not work is the VkTable Sort Column, because it doesn't exist in UIkit. But you can import it less code in your theme build workflow if ever needed.
